format = """\
    $username\
    $hostname\
    $directory\
    $git_branch\
    $git_commit\
    $git_state\
    $git_status\
    $hg_branch\
    $docker_context\
    $package\
    $dotnet\
    $elixir\
    $elm\
    $erlang\
    $golang\
    $java\
    $julia\
    $nim\
    $nodejs\
    $ocaml\
    $php\
    $purescript\
    $python\
    $ruby\
    $rust\
    $terraform\
    $zig\
    $nix_shell\
    $conda\
    $memory_usage\
    $kubernetes\
    $aws\
    $env_var\
    $crystal\
    $cmd_duration\
    $custom\
    $line_break\
    $jobs\
    $battery\
    $time\
    $character\
    """

[kubernetes]
symbol = "☸ "
disabled = false

[[kubernetes.contexts]]
context_pattern = "lumiquote-dev"
context_alias = "Azure (Dev)"

[[kubernetes.contexts]]
context_pattern = "lumiquote-prod-germanywestcentral"
context_alias = "Azure (Prod)"

[aws]
disabled = true

